pure_pursuit:
  ros__parameters:
    waypoints_path: "/home/misys/f1tenth_ws/src/CL2-UWaterloo/pure_pursuit/racelines/traj_light.csv"
    odom_topic: "/pf/pose/odom"
    car_refFrame: "laser"
    global_refFrame: "map"
    drive_topic: "/auto"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    # min_lookahead: 0.5 # for square track
    min_lookahead: 0.5 # for larger track
    max_lookahead: 3.0 # lookahead when the car is going around max velocity
    lookahead_ratio: 8.0 # approximately the max velocity
    # K_p: 0.25 # for square track
    # K_p: 0.15 # for big track
    K_p: 0.5
    steering_limit: 25.0
    velocity_percentage: 1.0 # the limit, can only do 1 lap with clean tires

    # PID controller Parameters
    Kp: 1.0
    Ki: 0.0
    Kd: 0.1
    target_speed: 5.0

waypoint_visualizer_node:
  ros__parameters:
    waypoints_path: "/home/misys/f1tenth_ws/src/CL2-UWaterloo/pure_pursuit/racelines/traj_light.csv"
